"""Add onboarding fields to profile

Revision ID: 273e61194777
Revises: db02c9feb744
Create Date: 2026-09-29 13:10:24.114735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273e61194777'
down_revision: Union[str, Sequence[str], None] = 'db02c9feb744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('college', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('state', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('career_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'career_preferences')
    op.drop_column('profiles', 'experience_level')
    op.drop_column('profiles', 'state')
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'graduation_year')
    op.drop_column('profiles', 'branch')
    op.drop_column('profiles', 'degree')
    op.drop_column('profiles', 'college')
    # ### end Alembic commands ###
