"""Add resume status and skill evidence classifications

Revision ID: 743b10989dae
Revises: 273e61194777
Create Date: 2026-09-29 13:41:01.817709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743b10989dae'
down_revision: Union[str, Sequence[str], None] = '273e61194777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('status', sa.String(), nullable=False))
    op.add_column('resumes', sa.Column('extracted_data', sa.JSON(), nullable=True))
    op.add_column('skill_evidence', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('skill_evidence', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('skill_evidence', sa.Column('recency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_evidence', 'recency')
    op.drop_column('skill_evidence', 'confidence')
    op.drop_column('skill_evidence', 'classification')
    op.drop_column('resumes', 'extracted_data')
    op.drop_column('resumes', 'status')
    # ### end Alembic commands ###
