"""Enhance readiness models with evidence and weights

Revision ID: 7cd2b8adcdf9
Revises: d10e243f8888
Create Date: 2026-09-29 14:07:00.508333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd2b8adcdf9'
down_revision: Union[str, Sequence[str], None] = 'd10e243f8888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readiness_breakdowns', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('readiness_breakdowns', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('readiness_breakdowns', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('readiness_scores', sa.Column('skill_match_summary', sa.JSON(), nullable=True))
    op.add_column('readiness_scores', sa.Column('weights_used', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readiness_scores', 'weights_used')
    op.drop_column('readiness_scores', 'skill_match_summary')
    op.drop_column('readiness_breakdowns', 'explanation')
    op.drop_column('readiness_breakdowns', 'evidence')
    op.drop_column('readiness_breakdowns', 'weight')
    # ### end Alembic commands ###
