"""Add market data columns to target_roles

Revision ID: bd47d8a80095
Revises: c5e87a134d20
Create Date: 2026-09-29 16:36:12.153588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd47d8a80095'
down_revision: Union[str, Sequence[str], None] = 'c5e87a134d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_embedding_hnsw'), table_name='resources', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_skills_embedding_hnsw'), table_name='skills', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_skills_embedding_hnsw'), 'skills', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_resources_embedding_hnsw'), 'resources', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
