"""Add taxonomy fields to skills and roles

Revision ID: d10e243f8888
Revises: 743b10989dae
Create Date: 2026-09-29 13:58:15.262443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10e243f8888'
down_revision: Union[str, Sequence[str], None] = '743b10989dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('aliases', sa.JSON(), nullable=True))
    op.add_column('skills', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('importance', sa.Integer(), nullable=True))
    op.add_column('target_roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('target_roles', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('target_roles', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_roles', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('target_roles', 'category')
    op.drop_column('target_roles', 'description')
    op.drop_column('skills', 'importance')
    op.drop_column('skills', 'difficulty')
    op.drop_column('skills', 'aliases')
    op.drop_column('skills', 'description')
    # ### end Alembic commands ###
